In [1]:
import numpy as np
from sklearn.cluster import KMeans
# 待聚类数据
dataSet = np.array([[8.7,9.0],[4.2,3.6],[12.0,7.5],[5.8,4.0],[7.4,4.3],[5,6.5],[5.9,5.8],[8.1,7.3]])

In [2]:
dataSet

array([[ 8.7,  9. ],
       [ 4.2,  3.6],
       [12. ,  7.5],
       [ 5.8,  4. ],
       [ 7.4,  4.3],
       [ 5. ,  6.5],
       [ 5.9,  5.8],
       [ 8.1,  7.3]])

In [3]:
kmeans_model = KMeans(n_clusters=2, random_state=100)
kmeans_model.fit(dataSet)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=100, tol=0.0001, verbose=0)

In [4]:
kmeans_model.labels_

array([0, 1, 0, 1, 1, 1, 1, 0], dtype=int32)

In [5]:
kmeans_model.cluster_centers_

array([[9.6       , 7.93333333],
       [5.66      , 4.84      ]])