# markdown sample

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])

In [2]:
arr

array([1, 2, 3, 4])

In [3]:
pwd

'/home/tarena/AID2008/month06/day02'

In [4]:
%run ../day01/demo_numpy.py

[1, 2, 3, 4]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


# 项目名称

*项目描述*

## 读取数据

## 数据描述性分析

1. python
2. java
3. c

* python
* java
* c

$$E=mc^2$$

$$z=\frac{x}{y}$$